# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2805f5caa63092564b5b3ac33e53d4569a31083b9a58a776247239e0152759c69a573f1118c1f5a6d458defc23769e667ba98d7cfb978736a5ec8c3d516db2cc

test:
  secret_key_base: 3c901f19be6f8d0fa90bcadacfbaa14e8aef40739847eb34dd29a3c9fba69827da6793946da597df012c2dddf25d4fc845cff571dbe9a69b7a55e2d18229dfe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
