export User from '../../containers/admins/User.jsx'
export UserList from '.././admin/UserList.jsx'
export Categories from '../../containers/admins/Categories.jsx'
export AdminProducts from '../../containers/admins/AdminProducts.jsx'
export CreateCategories from '../../containers/admins/CreateCategories.jsx'
export EditCategories from '../../containers/admins/EditCategories.jsx'
export AdminProductList from './AdminProductList.jsx'
export CategoriesList from './CategoriesList.jsx'
